[lint]
select = ["ALL"]

ignore = [
    "T201",    # ignore printing
    "FA102",   # future-required-type-annotation
    "PERF203", # try-except-in-loop
    "D100",    # missing docstring
    "F401",    # missing imports
    "ANN101",  # missing-type-self
    "RUF001",  # ambiguous-unicode-character-string
    "DTZ007",  # quit bugging me about timezones
    "PD901",   # don't name pandas df
]
